version: "3.7"
services:
  api-gateway:
    image: ${IMAGE_NAME}
    volumes: 
      - $HOME/.gateway-config/:/app/build/config-management/config
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s