name: Test Runner for API gateway

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set environmental variable
        run: echo ::set-env name=IMAGE_NAME::$(echo docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:$(date "+%d%m%y%H%M"))

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test
